#Obtener Test
GET http://localhost:3500/dog/random-dog

###
#Obtener Test
GET http://localhost:3500/dog/pipe-dog


###
#Obtener Test
GET http://localhost:4000/random-dog

###
#Obtener Test
GET http://localhost:3500/random-dog