#GET Test API
GET http://localhost:3000/dog/random-dog

###
#GET Test API - PIPE
GET http://localhost:3000/dog/pipe-dog


###
#GET Test API - KOA
GET http://localhost:4000/random-dog

###
#GET Test API - Express
GET http://localhost:3500/random-dog