version: "3.8"

services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    networks:
      - perf-test-net

  rust-api:
    build: ./rust
    container_name: rust-api
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    depends_on:
      - mongodb
    networks:
      - perf-test-net

  quarkus-api:
    build: ./quarkus
    platform: linux/amd64
    container_name: quarkus-api
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    depends_on:
      - mongodb
    networks:
      - perf-test-net

  node-api:
    build: ./node
    container_name: node-api
    ports:
      - "8083:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    depends_on:
      - mongodb
    networks:
      - perf-test-net

networks:
  perf-test-net:
    driver: bridge
