export const xp = [
  {
    from: '04/2014',
    to: '10/2014',
    company: 'Antel',
    level: 'Trainee',
    location: 'Montevideo',
    project: 'e-Commerce',
    description: 'Developing java libraries, utilities and a management web.',
    technologies: ['JAVAEE', 'jBoss', 'WS-RESTful', 'JSF', 'Richfaces', 'Primefaces', 'EJB', 'JPA', 'Hibernate',
      'MySQL', 'Postgres', 'Mercurial', 'Kanban'],
  }, {
    from: '10/2014',
    to: '03/2017',
    company: 'Antel',
    level: 'Junior-Middle',
    location: 'Montevideo',
    project: 'payment gateway',
    description: 'Developing Backoffice web, Proxy web, B2B and W2W integrations.',
    technologies: ['JAVAEE', 'Camel', 'SwitchYard', 'Fuse services works', 'EJB', 'JMS', 'WS-SOAP', 'WS-Security',
      'WS-Addressing', 'jBoss', 'JSF', 'Primefaces', 'Web sockets', 'JPA', 'Postgres', 'Solr', 'Vagrant', 'Git',
      'Scrum'],
  }, {
    from: '03/2017',
    to: '08/2017',
    company: 'Antel',
    level: 'Middle',
    location: 'Montevideo',
    project: 'order-manager',
    description: 'Integrating applications via web services.',
    technologies: ['OSGI', 'Docker', 'MongoDB', 'Scala', 'Karaf', 'WS-RESTful', 'WS-SOAP', 'Swagger', 'Git', 'Scrum'],
  }, {
    from: '08/2017',
    to: '04/2018',
    company: 'Antel',
    level: 'Middle',
    location: 'Montevideo',
    project: 'SUR',
    description: 'Developing help desk and support application.',
    technologies: ['Docker', 'Docker-compose', 'Postgres', 'WildFly 10', 'JAVAEE', 'Vaadin 7', 'Camunda', 'Infinispan',
      'Mercurial', 'Scrum'],
  }, {
    from: '04/2018',
    to: '10/2018',
    company: 'Urudata',
    level: 'Senior',
    location: 'Montevideo',
    project: 'Nuevo Manantial',
    description: "Maintaining Nuevo Manantial's applications.",
    technologies: ['JBPM kie-Server', 'NodeJS', 'Bower', 'Grunt', 'Angular', 'ReactJS', 'Spring-Boot', 'SQLServer',
      'SVN', 'GIT', 'Scrum'],
  }, {
    from: '03/2019',
    to: '10/2019',
    company: 'Antel',
    level: 'Senior',
    location: 'Montevideo',
    project: 'SUR',
    description: 'Developing help desk and support application.',
    technologies: ['Postgres', 'WildFly 10', 'JAVAEE', 'Camunda', 'Infinispan', 'Kubernetes', 'Spring-Boot',
      'Vaadin 14', 'GIT', 'Scrumban'],
  }, {
    from: '11/2019',
    to: '02/2022',
    company: 'BASF',
    level: 'Specialist',
    location: 'Montevideo',
    project: 'Chatbots & Web Systems',
    description: 'Application Design, Research & Development. Tech Leader. Interim Architect.',
    technologies: ['Vue', 'Vuex', 'Nuxt', 'ReactJS', 'React Native', 'Redux', 'Express', 'Sequelize', 'NodeJS',
      'Vaadin', 'Spring-Boot', 'Docker', 'Kubernetes', 'Cloud Foundry', 'Watson', 'SAP CAI', 'Intrexx', 'OutSytems',
      'Genexus', 'Gitlab CI/CD', 'Jira', 'Scrum'],
  }, {
    from: '03/2022',
    to: 'today',
    company: 'Perficient',
    level: 'Specialist',
    location: 'Montevideo',
    project: 'XPO Logistics - Rating',
    description: 'Design & develop of the rating module at XPO.',
    technologies: ['GIT', 'JAVAEE', 'Liberty', 'Jira', 'Scrum'],
  },
]
